-- Interplatform Requests - Data Stage
-- Entry point that wires in all prototype definitions.
-- NOTE: Per-planet interplatform locations are generated in data-final-fixes.lua
-- so that planets added by other mods are included.
